### ISSUE TITLE
0.6.0 release broken?

### ISSUE THREAD

**Issue by axic** [pepyakin/binaryen-rs#32]
I get:
```
[binaryen-sys 0.6.0] fatal: Not a git repository (or any of the parent directories): .git
```

Which is produced by https://github.com/pepyakin/binaryen-rs/blob/master/binaryen-sys/build.rs#L141

Does cargo download these crates with their .git data?

**Comment by axic** [comment]
ping @pepyakin

**Comment by pepyakin** [comment]
oooops, sorry for missing!

I just checked on a clean project and can't reproduce the issue... If I create an empty project on a clean machine and add binaryen as a dependency it builds fine.

Yes, the crates.io package should have been packed along with binaryen git repo (excluding tests)...

**Comment by axic** [comment]
Here's an example: https://circleci.com/gh/wasmx/wasm-chisel/281

**Comment by pepyakin** [comment]
Hm, but looks like it about a different issue:

> fatal: Not a git repository (or any of the parent directories): .git
wrapper.h:1:10: fatal error: 'stdbool.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by axic** [comment]
That `stdbool.h` stuff is different, still don't know why any of the gcc packages don't have it, but the git issue is shown before that.

**Comment by pepyakin** [comment]
That's interesting! I also noticed that there is a compile error somehow related to #24 , will take a look

**Comment by axic** [comment]
Yeah the missing `stdbool.h` is super annoying, only happens on circleci, nobody is able to reproduce it with clang or gcc on linux or mac.

**Comment by pepyakin** [comment]
The line

```
fatal: Not a git repository (or any of the parent directories): .git
```

is coming from `git` and is not actually fatal, the repo is embedded to the crate.

So the main thing that fails the build is that CC can't find the `stdbool.h` header.

**Comment by axic** [comment]
@pepyakin can you release 0.7.0 and see if it fixes anything?

**Comment by pepyakin** [comment]
@axic [done](https://crates.io/crates/binaryen)!

**Comment by axic** [comment]
This was a CI issue: https://github.com/wasmx/wasm-chisel/pull/61#issuecomment-492030751
