### ISSUE TITLE
Upgrade binaryen-sys?

### ISSUE THREAD

**Issue by RReverser** [pepyakin/binaryen-rs#39]
binaryen-sys crate seems to reference a fairly outdated version of binaryen by now. Any chance of updating it to latest 1.39.1? It contains a bunch of useful functions, including for enumerating functions, so that one can actually iterate over the module and perform transformations on code.

**Comment by axic** [comment]
This can be closed since #48 was merged.

**Comment by pepyakin** [comment]
Oops, sorry for missing this!
